version: '3'

services:

  nginx:  
    image: nginx:1.17
    container_name: nginx
    networks:
      - net-desafio-docker-compose-node-mysql
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app

  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: npm start
    networks:
      - net-desafio-docker-compose-node-mysql
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - net-desafio-docker-compose-node-mysql

networks:
  net-desafio-docker-compose-node-mysql:
    driver: bridge


    